# Generated by Django 5.0.7 on 2024-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_invoice_status_receipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('P', 'Оплачено'), ('U', 'Не оплачено'), ('C', 'На проверке'), ('R', 'Отказано')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cash_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('P', 'Оплачено'), ('U', 'Не оплачено'), ('C', 'На проверке'), ('R', 'Отказано')], default='U', max_length=1),
        ),
    ]
