# Generated by Django 5.0.7 on 2024-07-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_invoice_status_receipt_cash_rate_alter_receipt_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('A', 'Ожидание Админа'), ('B', 'Ожидание Пользователя'), ('C', 'Ожидание оплаты'), ('D', 'Проверка'), ('R', 'Отказано')], default='A', max_length=1),
        ),
    ]
