# Generated by Django 5.0.7 on 2024-07-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_remove_invoice_status_alter_receipt_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cash_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, upload_to='receipt/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('A', 'На проверке'), ('B', 'Ожидание Соглашение'), ('C', 'Ожидание Оплаты'), ('D', 'Оплачено')], default='A', max_length=1),
        ),
    ]
