# Generated by Django 5.0.7 on 2024-07-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_invoice_paid_date_alter_receipt_cash_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.invoice'),
        ),
    ]
