# Generated by Django 5.0.7 on 2024-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_alter_receipt_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_rate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer_detail',
            field=models.CharField(default=5, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_detail',
            field=models.CharField(default=5, max_length=250),
            preserve_default=False,
        ),
    ]
