# Generated by Django 5.0.7 on 2024-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_dailycashrate_remove_invoice_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_information', models.TextField(default='Bank Russian : Номер 2553039389393')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
            },
        ),
        migrations.AlterModelOptions(
            name='dailycashrate',
            options={'verbose_name': 'Курс волюты'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Список Инвойсов'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Список Чеков'},
        ),
    ]
