# Generated by Django 5.0.7 on 2024-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_paymentinformation_alter_dailycashrate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCashRate',
        ),
        migrations.AlterModelOptions(
            name='paymentinformation',
            options={'verbose_name': 'Настройки информации'},
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='cash_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_information',
            field=models.TextField(default='Банк Мира'),
        ),
    ]
