# Generated by Django 5.0.7 on 2024-07-28 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_delete_dailycashrate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Список  дел'},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='image',
        ),
        migrations.AddField(
            model_name='receipt',
            name='agent_report',
            field=models.TextField(blank=True, default='Пусто'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='completed_act',
            field=models.TextField(blank=True, default='Пусто'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sub_agent',
            field=models.TextField(blank=True, default='Инфо'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='swift',
            field=models.FileField(blank=True, upload_to='swift/'),
        ),
    ]
