# Generated by Django 5.0.7 on 2024-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_alter_receipt_options_remove_receipt_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('A', 'Ожидание Оплаты'), ('B', 'Ожидание Соглашение'), ('C', 'На проверке'), ('D', 'Оплачено')], default='A', max_length=1),
        ),
    ]
